'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createCosmos} from './cosmos';
export type Zone='task'|'link'|'image';
const zones:Zone[]=['task','link','image'];
const vertex=`varying vec3 vP; varying vec3 vN; void main(){vP=position;vN=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
const fragment=`precision highp float;
varying vec3 vP;varying vec3 vN;uniform vec3 c1;uniform vec3 c2;uniform float mode;uniform float time;
float hash(vec3 p){p=fract(p*.3183099+vec3(.1,.2,.3));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float noise(vec3 x){vec3 i=floor(x),f=fract(x);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float f=0.,a=.5;for(int i=0;i<6;i++){f+=a*noise(p);p=p*2.04+4.3;a*=.5;}return f;}
void main(){vec3 p=normalize(vP);float f=fbm(p*5.0+fbm(p*8.)*2.);float fine=fbm(p*45.);float band=sin((p.y+f*.26)*42.);float tex=mode<.5?f*.72+fine*.28:mode<1.5?f*.7+band*.09+fine*.18:f*.65+fine*.35;vec3 col=mix(c1,c2,smoothstep(.25,.7,tex));vec3 n=normalize(vN);float light=max(dot(n,normalize(vec3(-.65,.7,1.))),0.);float limb=pow(1.-max(dot(n,vec3(0,0,1.)),0.),3.);col*=.11+light*.95;col+=c2*limb*.13;gl_FragColor=vec4(col,1.);}`;
export default function Scene({selected,onSelect,onReady,resetToken,motion}:{selected:Zone|null;onSelect:(z:Zone)=>void;onReady:(ok:boolean)=>void;resetToken:number;motion:boolean}){const host=useRef<HTMLDivElement>(null),control=useRef<{go:(zone:Zone|null)=>void;camera:THREE.PerspectiveCamera;controls:OrbitControls}|null>(null),select=useRef(onSelect);const moving=useRef(motion);useEffect(()=>{select.current=onSelect;moving.current=motion;},[onSelect,motion]);
useEffect(()=>{const el=host.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{onReady(false);return;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x070b0e);renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,200),controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.dampingFactor=.045;controls.minDistance=3;controls.maxDistance=28;controls.rotateSpeed=.36;controls.zoomSpeed=.5;controls.minPolarAngle=.45;controls.maxPolarAngle=2.45;
const narrow=el.clientWidth<650;const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');renderer.setPixelRatio(Math.min(devicePixelRatio,narrow?1.5:1.7));const positions=narrow?[new THREE.Vector3(-1.8,2,0),new THREE.Vector3(1.9,.2,-2),new THREE.Vector3(-.45,-2.5,1)]:[new THREE.Vector3(-3.15,.6,0),new THREE.Vector3(2.8,1.9,-2),new THREE.Vector3(1,-2.3,1)];const sizes=[1.55,1.32,1.1];const colors=[[0x321c0d,0xe4ad69],[0x123331,0x8fafac],[0x272c38,0xc0c4d0]];const meshes:THREE.Mesh[]=[];const rotators:THREE.Group[]=[];
positions.forEach((p,i)=>{const group=new THREE.Group();group.position.copy(p);scene.add(group);rotators.push(group);const mat=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms:{c1:{value:new THREE.Color(colors[i][0])},c2:{value:new THREE.Color(colors[i][1])},mode:{value:i},time:{value:0}}});const sphere=new THREE.Mesh(new THREE.SphereGeometry(sizes[i],72,48),mat);sphere.userData.zone=zones[i];group.add(sphere);meshes.push(sphere);
const atm=new THREE.Mesh(new THREE.SphereGeometry(sizes[i]*1.026,48,32),new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:`varying vec3 vN;uniform vec3 color;void main(){float a=pow(1.-abs(dot(normalize(vN),vec3(0,0,1.))),4.)*.18;gl_FragColor=vec4(color,a);}`,uniforms:{color:{value:new THREE.Color(colors[i][1])}},transparent:true,depthWrite:false,side:THREE.BackSide,blending:THREE.AdditiveBlending}));group.add(atm);
if(i===1){const ring=new THREE.Mesh(new THREE.RingGeometry(1.8,2.3,160),new THREE.MeshBasicMaterial({color:0x819690,transparent:true,opacity:.19,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=1.2;ring.rotation.y=.2;group.add(ring);for(const r of [1.86,2.06,2.26]){const line=new THREE.Mesh(new THREE.RingGeometry(r,r+.012,128),new THREE.MeshBasicMaterial({color:0xabb1a3,transparent:true,opacity:.3,side:THREE.DoubleSide}));line.rotation.copy(ring.rotation);group.add(line);}}
});
const cosmos=createCosmos(narrow,renderer.getPixelRatio());scene.add(cosmos.sky);
const orbit=new THREE.EllipseCurve(0,0,5.7,4.0,0,Math.PI*2,false,0);const path=new THREE.BufferGeometry().setFromPoints(orbit.getPoints(200).map(p=>new THREE.Vector3(p.x,p.y,-2.5)));scene.add(new THREE.LineLoop(path,new THREE.LineBasicMaterial({color:0x4c4940,transparent:true,opacity:.16})));
let transition:{p:THREE.Vector3,t:THREE.Vector3}|null=null;const home=()=>{const narrow=el.clientWidth<650;return new THREE.Vector3(0,.15,narrow?22.5:15);};camera.position.copy(home());controls.target.set(0,0,0);const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();};resize();const observer=new ResizeObserver(resize);observer.observe(el);
control.current={go:(z:Zone|null)=>{const i=z?zones.indexOf(z):-1;transition=i<0?{p:home(),t:new THREE.Vector3(0,0,0)}:{p:positions[i].clone().add(new THREE.Vector3(0,.2,el.clientWidth<650?7.8:6.8)),t:positions[i].clone()};},camera,controls};const start=()=>{transition=null;};controls.addEventListener('start',start);let down={x:0,y:0},drag=false;const pd=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};drag=false;};const pm=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)drag=true;};const pu=(e:PointerEvent)=>{if(drag)return;const b=el.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=ray.intersectObjects(meshes)[0];if(hit)select.current(hit.object.userData.zone);};el.addEventListener('pointerdown',pd);el.addEventListener('pointermove',pm);el.addEventListener('pointerup',pu);let frame=0,prev=0;function loop(t:number){frame=requestAnimationFrame(loop);if(document.hidden)return;const dt=Math.min((t-prev)/1000,.05);prev=t;if(transition){const speed=reducedMotion.matches?1:.065;camera.position.lerp(transition.p,speed);controls.target.lerp(transition.t,speed);if(camera.position.distanceTo(transition.p)<.02)transition=null;}if(moving.current&&!reducedMotion.matches){rotators.forEach((g,i)=>{g.children[0].rotation.y+=dt*(.019+i*.006);});cosmos.update(dt);}controls.update();renderer.render(scene,camera);}frame=requestAnimationFrame(loop);onReady(true);
const lost=(e:Event)=>{e.preventDefault();onReady(false);};renderer.domElement.addEventListener('webglcontextlost',lost);return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();scene.traverse(o=>{const mesh=o as THREE.Mesh;mesh.geometry?.dispose();if(mesh.material){if(Array.isArray(mesh.material)){mesh.material.forEach(m=>m.dispose());}else{mesh.material.dispose();}}});renderer.dispose();el.removeEventListener('pointerdown',pd);el.removeEventListener('pointermove',pm);el.removeEventListener('pointerup',pu);el.replaceChildren();};},[onReady]);
useEffect(()=>{control.current?.go(selected);},[selected,resetToken]);return <div ref={host} className="universe" role="img" aria-label="ثلاثة عوالم تفاعلية للعمل والمشاريع والصور وسط نجوم ومجرة حلزونية. اسحب للدوران وقرب بإصبعين؛ أزرار العوالم متاحة أسفل الشاشة"/>;}
