'use client';

import {useCallback,useEffect,useRef,useState} from 'react';
import {BriefcaseBusiness,Code2,Image as ImageIcon,LockKeyhole,Pause,Play,Orbit,Plus,X,Pencil,Trash2,ExternalLink,LoaderCircle,Upload,RotateCcw,Check,CloudOff} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import dynamic from 'next/dynamic';
import type {Zone} from './scene';
const Scene=dynamic(()=>import('./scene'),{ssr:false,loading:()=> <div className="universe"/>});

type Item={id:string;kind:'task'|'link';title:string;url:string;note:string;done:number;deleted:number};
type Photo={id:string;title:string;created:number;deleted:number};
type Editor={kind:Zone;item?:Item|Photo};
const names={task:'مساحة العمل',link:'المشاريع',image:'الصور'};
const icons={task:BriefcaseBusiness,link:Code2,image:ImageIcon};
const additions={task:'مهمة جديدة',link:'رابط جديد',image:'إضافة صورة'};
async function request<T=Record<string,unknown>>(path:string,options?:RequestInit){const response=await fetch(path,{...options,cache:'no-store'});const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error||'تعذر الاتصال. حاول مرة أخرى');return body;}
export default function World(){
 const [trash,setTrash]=useState(false);
 const [zone,setZone]=useState<Zone|null>(null),[items,setItems]=useState<Item[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[ready,setReady]=useState<boolean|null>(null),[motion,setMotion]=useState(false),[reset,setReset]=useState(0),[hint,setHint]=useState(true),[editor,setEditor]=useState<Editor|null>(null),[view,setView]=useState<Photo|null>(null),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(''),[url,setUrl]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[formError,setFormError]=useState('');
 const upload=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{setLoading(true);setLoadError('');try{const [a,b]=await Promise.all([request<Item[]>('/api/items'),request<Photo[]>('/api/images')]);setItems(a);setPhotos(b);}catch(e){setLoadError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const initialize=setTimeout(()=>{void load();setMotion(!mq.matches&&localStorage.getItem('k7-motion')!=='off');},0);const change=()=>setMotion(!mq.matches);mq.addEventListener('change',change);const timer=setTimeout(()=>setHint(false),8500);return()=>{clearTimeout(initialize);clearTimeout(timer);mq.removeEventListener('change',change);};},[load]);
 const select=useCallback((z:Zone)=>{setZone(z);setTrash(false);setHint(false);},[]);
 const home=()=>{setZone(null);setReset(n=>n+1);};
 const openEditor=(kind:Zone,item?:Item|Photo)=>{setEditor({kind,item});setTitle(item?.title||'');setUrl(item&&'url'in item?item.url:'');setNote(item&&'note'in item?item.note:'');setFile(null);setFormError('');};
 const patch=async(kind:Zone,id:string,data:Record<string,unknown>)=>{await request(kind==='image'?'/api/images':'/api/items',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...data})});await load();};
 const archive=async(kind:Zone,id:string)=>{try{await patch(kind,id,{deleted:true});setView(null);toast('نُقل إلى المحذوفات',{action:{label:'تراجع',onClick:()=>{void patch(kind,id,{deleted:false}).catch(e=>toast.error(e.message));}}});}catch(e){toast.error((e as Error).message);}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editor)return;setBusy(true);setFormError('');try{if(editor.item){await patch(editor.kind,editor.item.id,{title,...(editor.kind!=='image'?{url,note}:{})});}else if(editor.kind==='image'){if(!file)throw new Error('اختر صورة أولاً');const data=new FormData();data.set('file',file);data.set('title',title||file.name);await request('/api/images',{method:'POST',body:data});await load();}else{await request('/api/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:editor.kind,title,url,note})});await load();}setEditor(null);toast.success('تم الحفظ');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}};
 register({name:'open_world',description:'Navigate to the work, projects or images region. Does not change saved content.',inputSchema:{type:'object',properties:{region:{type:'string',enum:['task','link','image']}},required:['region'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{const region=(input as {region?:Zone})?.region;if(!region||!['task','link','image'].includes(region))throw new Error('Invalid region');select(region);return {region};}});
 register({name:'list_saved_items',description:'Read the signed-in user’s saved tasks, project links and image metadata.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const [items,images]=await Promise.all([request<Item[]>('/api/items'),request<Photo[]>('/api/images')]);return{items,images};}});
 register({name:'create_task',description:'Save a task in the signed-in user’s private workspace.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:160},note:{type:'string',maxLength:2000}},required:['title'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const data=input as {title?:string;note?:string};if(typeof data?.title!=='string'||!data.title.trim()||data.title.length>160||data.note!==undefined&&typeof data.note!=='string')throw new Error('Invalid task');const result=await request('/api/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'task',...data})});await load();select('task');return{id:result.id};}});return()=>controller.abort();},[load,select]);
 const rows=zone==='image'?photos.filter(p=>!!p.deleted===trash):items.filter(i=>i.kind===zone&&!!i.deleted===trash);const Icon=zone?icons[zone]:Orbit;
 return <main className={`world ${zone?'is-focused':''}`}>
  <Scene selected={zone} onSelect={select} onReady={setReady} resetToken={reset} motion={motion}/><div className="vignette"/>
  <header className="topbar"><div className="identity"><span className="wordmark" aria-label="عالم خالد">K7</span><span className="private" title="خاص بك"><LockKeyhole size={14}/><span className="sr-only">خاص بك</span></span></div><div className="top-actions"><button className="icon-button" aria-label={motion?'إيقاف الحركة':'تشغيل الحركة'} title={motion?'إيقاف الحركة':'تشغيل الحركة'} onClick={()=>{setMotion(!motion);localStorage.setItem('k7-motion',motion?'off':'on');}}>{motion?<Pause size={17}/>:<Play size={17}/>}</button><button className="icon-button" aria-label="العودة إلى العالم" title="العودة إلى العالم" onClick={home}><Orbit size={22}/></button></div></header>
  {ready===null&&<div className="scene-status"><LoaderCircle className="spin" size={22}/></div>}
  {ready===false&&<div className="fallback"><Orbit size={48}/><span>العوالم متاحة من الأسفل</span></div>}
  {hint&&!zone&&ready&&<p className="gesture-hint">اسحب للتجول · اختر عالماً</p>}
  <Sheet open={zone!==null} modal={false} onOpenChange={open=>{if(!open)setZone(null);}}><SheetContent className="workspace" showCloseButton={false} onInteractOutside={e=>e.preventDefault()} onOpenAutoFocus={e=>e.preventDefault()} aria-describedby="world-description"><div className="panel-head"><div className="panel-name"><Icon size={19}/><SheetTitle>{trash?'المحذوفات':zone?names[zone]:''}</SheetTitle></div><div className="panel-actions"><button className="icon-button" aria-label={trash?'العودة للمحتوى':'المحذوفات'} title={trash?'العودة للمحتوى':'المحذوفات'} onClick={()=>setTrash(!trash)}>{trash?<RotateCcw size={16}/>:<Trash2 size={16}/>}</button><button className="icon-button" aria-label="إغلاق المساحة" onClick={()=>setZone(null)}><X size={18}/></button></div></div><SheetDescription id="world-description" className="sr-only">المحتوى محفوظ في مساحتك الخاصة</SheetDescription><div className="panel-scroll">
  {loading?<div className="empty" role="status"><LoaderCircle className="spin" size={24}/><span className="sr-only">تحميل</span></div>:loadError?<div className="empty"><CloudOff size={28}/><p role="alert">{loadError}</p><button className="text-button" onClick={()=>void load()}>إعادة المحاولة</button></div>:rows.length===0?<div className="empty"><Icon size={34} strokeWidth={1}/><p>{trash?'لا توجد محذوفات':zone==='task'?'مساحة لفكرتك القادمة':zone==='link'?'أعمالك في مكان واحد':'احتفظ بما يلهمك'}</p></div>:trash?<div className="items">{rows.map(item=><article key={item.id} className="item"><div className="item-main"><p>{item.title}</p></div><button className="icon-button" aria-label={`استعادة ${item.title}`} onClick={()=>{if(zone)void patch(zone,item.id,{deleted:false}).catch(e=>toast.error(e.message));}}><RotateCcw size={18}/></button></article>)}</div>:zone==='image'?<div className="gallery">{(rows as Photo[]).map(p=><button key={p.id} className="photo" onClick={()=>setView(p)} aria-label={`عرض ${p.title}`}><img src={`/api/images?id=${encodeURIComponent(p.id)}`} alt={p.title} loading="lazy"/><span>{p.title}</span></button>)}</div>:<div className="items">{(rows as Item[]).map(item=><article key={item.id} className={`item ${item.done?'done':''}`}>{zone==='task'&&<Checkbox className="check-button" checked={!!item.done} aria-label={`إكمال ${item.title}`} onCheckedChange={checked=>{void patch('task',item.id,{done:!!checked}).catch(e=>toast.error(e.message));}}/>}<div className="item-main">{zone==='link'?<a className="project-link" href={item.url} target="_blank" rel="noopener noreferrer">{item.title}<ExternalLink size={14}/></a>:<p>{item.title}</p>}{item.note&&<span>{item.note}</span>}{zone==='link'&&<small dir="ltr">{new URL(item.url).hostname}</small>}</div><div className="row-actions"><button className="icon-button" aria-label={`تعديل ${item.title}`} onClick={()=>openEditor(item.kind,item)}><Pencil size={14}/></button><button className="icon-button" aria-label={`حذف ${item.title}`} onClick={()=>void archive(item.kind,item.id)}><Trash2 size={14}/></button></div></article>)}</div>}
  </div><div className="panel-foot"><button className="add-button" onClick={()=>{setTrash(false);if(zone)openEditor(zone);}} disabled={!!loadError||loading}><Plus size={17}/>{zone?additions[zone]:''}</button><span className="count" aria-label="عدد العناصر">{rows.length.toString().padStart(2,'0')}</span></div></SheetContent></Sheet>
  <nav className="world-dock" aria-label="العوالم">{(['task','link','image'] as Zone[]).map(z=>{const I=icons[z];return <button key={z} className={`world-button ${zone===z?'active':''}`} aria-label={names[z]} aria-pressed={zone===z} onClick={()=>select(z)}><span className={`mini-orb ${z}`}/><I size={21} className="dock-icon"/><span className="dock-label">{names[z]}</span></button>;})}</nav>
  <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!busy)setEditor(null);}}><DialogContent className="editor" showCloseButton={false}><div className="editor-head"><DialogTitle>{editor?.item?'تعديل':editor?additions[editor.kind]:''}</DialogTitle><button className="icon-button" aria-label="إغلاق التحرير" disabled={busy} onClick={()=>setEditor(null)}><X size={20}/></button></div><DialogDescription className="sr-only">أضف المحتوى إلى مساحتك الخاصة</DialogDescription><form onSubmit={save}>
  {editor?.kind==='image'&&!editor.item&&<><input ref={upload} type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" tabIndex={-1} onChange={e=>{const f=e.target.files?.[0];setFile(f||null);setFormError(f&&f.size>8*1024*1024?'الحد الأقصى للصورة 8 ميجابايت':'');}}/><button type="button" className="upload-field" onClick={()=>upload.current?.click()}><Upload size={26}/><span>{file?file.name:'اختر صورة'}</span><small>JPG · PNG · WebP / 8 MB</small></button></>}
  <label htmlFor="item-title">{editor?.kind==='image'?'الاسم':'العنوان'}{editor?.kind==='image'&&!editor.item&&<span>اختياري</span>}</label><input id="item-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={160} required={editor?.kind!=='image'||!!editor.item} autoComplete="off"/>
  {editor?.kind==='link'&&<><label htmlFor="item-url">الرابط</label><input id="item-url" type="url" inputMode="url" dir="ltr" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/…" required/></>}
  {editor?.kind!=='image'&&<><label htmlFor="item-note">ملاحظة <span>اختياري</span></label><textarea id="item-note" rows={3} value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/></>}
  {formError&&<p className="form-error" role="alert">{formError}</p>}<button type="submit" className="save-button" disabled={busy||!!file&&file.size>8*1024*1024}>{busy?<LoaderCircle size={18} className="spin"/>:<Check size={18}/>}حفظ</button>
  </form></DialogContent></Dialog>
  <Dialog open={!!view} onOpenChange={open=>{if(!open)setView(null);}}><DialogContent className="lightbox" showCloseButton={false}><DialogTitle className="sr-only">{view?.title||'صورة'}</DialogTitle><DialogDescription className="sr-only">الصورة بالحجم الكامل</DialogDescription>{view&&<><img src={`/api/images?id=${encodeURIComponent(view.id)}`} alt={view.title}/><div className="lightbox-foot"><span>{view.title}</span><div><button className="icon-button" aria-label="تعديل اسم الصورة" onClick={()=>{openEditor('image',view);setView(null);}}><Pencil size={16}/></button><button className="icon-button" aria-label="حذف الصورة" onClick={()=>void archive('image',view.id)}><Trash2 size={16}/></button><button className="icon-button" aria-label="إغلاق الصورة" onClick={()=>setView(null)}><X size={20}/></button></div></div></>}</DialogContent></Dialog>
  <Toaster position="top-center" theme="dark" dir="rtl" closeButton toastOptions={{style:{background:'#171e22',color:'#e1d9cd',border:'1px solid #6c6049',fontFamily:'Tahoma, sans-serif'}}}/>
 </main>;
}
