import {db,bucket,identity,error,title,noCache} from '../../../db/raw';
export async function GET(req:Request){try{const owner=await identity(req),id=new URL(req.url).searchParams.get('id');if(id){const row=await db().prepare('SELECT * FROM images WHERE id=? AND owner=? AND deleted=0').bind(id,owner).first();if(!row)return new Response('Not found',{status:404});const obj=await bucket().get(String(row.object_key));if(!obj)return new Response('Not found',{status:404});return new Response(obj.body,{headers:{...noCache,'Content-Type':String(row.mime),'X-Content-Type-Options':'nosniff'}});}const data=await db().prepare('SELECT id,title,created,deleted FROM images WHERE owner=? ORDER BY created DESC').bind(owner).all();return Response.json(data.results,{headers:noCache});}catch(e){return error(e);}}
export async function POST(req:Request){try{const owner=await identity(req,true);if(Number(req.headers.get('content-length'))>9*1024*1024)return Response.json({error:'الحد الأقصى للصورة 8 ميجابايت'},{status:413});const form=await req.formData(),f=form.get('file');if(!(f instanceof File)||f.size>8*1024*1024||f.size===0)return Response.json({error:'اختر صورة بحجم أقل من 8 ميجابايت'},{status:400});const bytes=new Uint8Array(await f.arrayBuffer());let mime='';if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)mime='image/png';else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime='image/jpeg';else if(String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')mime='image/webp';if(!mime||mime!==f.type)return Response.json({error:'الصيغ المدعومة: JPG وPNG وWebP'},{status:400});const id=crypto.randomUUID(),key=owner+'/'+id;await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});try{await db().prepare('INSERT INTO images (id,owner,title,mime,object_key,deleted,created) VALUES (?,?,?,?,?,0,?)').bind(id,owner,title(form.get('title'))||title(f.name),mime,key,Date.now()).run();}catch(e){await bucket().delete(key);throw e;}return Response.json({id},{status:201});}catch(e){return error(e);}}
export async function PATCH(req:Request){try{
 const owner=await identity(req,true),b=await req.json() as Record<string,unknown>;if(typeof b.id!=='string')return Response.json({error:'الصورة غير صالحة'},{status:400});
 const old=await db().prepare('SELECT id FROM images WHERE id=? AND owner=?').bind(b.id,owner).first();if(!old)return Response.json({error:'الصورة غير موجودة'},{status:404});
 const fields:string[]=[],values:(string|number)[]=[];
 if(b.title!==undefined){const t=title(b.title);if(!t)return Response.json({error:'العنوان مطلوب'},{status:400});fields.push('title=?');values.push(t);}
 if(b.deleted!==undefined){if(typeof b.deleted!=='boolean')return Response.json({error:'القيمة غير صالحة'},{status:400});fields.push('deleted=?');values.push(b.deleted?1:0);}
 if(fields.length)await db().prepare('UPDATE images SET '+fields.join(',')+' WHERE id=? AND owner=?').bind(...values,b.id,owner).run();return Response.json({ok:true});
 }catch(e){return error(e);}}
